version: 2.1
executors:
  node:
    docker:
      - image: circleci/node
orbs:
  swissknife: roopakv/swissknife@0.37.0
jobs:
  trigger-needed-workflows:
    docker:
      - image: circleci/node:12
    working_directory: /home/circleci/project/
    steps:
      - checkout
      - swissknife/trigger-workflows-for-all-modified:
          base-branch: master
          run-mode-for-base-branch: run_for_last_commit
          use-divergence-point: true
          code-param-name-map: '
            [
              {"regex": "^(packages/api).*", "param_name": "run_api"},
              {"regex": "^(packages/app).*", "param_name": "run_app"},
              {"regex": "^(packages/gateway).*", "param_name": "run_gateway"}
            ]'
          additional-param-map: '{"run_trigger_workflow": false}'
          use-swissknife-sha: true
  build:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/packages/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - run:
          name: Content 
          command: |
            cat README.md 
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_name >> ..."
      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/<< parameters.package_name >>

  deploy:
    parameters:
      package_name:
        type: string

    executor: node
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
      REVISION: << pipeline.git.base_revision >>
    working_directory: ~/project/packages/<< parameters.package_name >>
    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job. 
      - swissknife/wait_for_workflow:
          max-wait-time: '1800'
          workflow-name: ^(app)$
          sleep-time-between-checks: '5'
      - run:
          name: Content to deploy
          command: echo "${CIRCLE_COMPARE_URL}"
      - run:
          name: Content to deploy
          command: echo "${REVISION}"
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_name >> ..."

workflows:
  trigger-needed-workflows:
    when: << pipeline.parameters.run_trigger_workflow >>
    jobs:
      - trigger-needed-workflows
  api:
    when: << pipeline.parameters.run_api >>
    jobs:
      - build:
          name: api-build
          package_name: api
      - deploy:
          name: api-deploy
          package_name: api
          requires:
            - api-build

  app:
    when: << pipeline.parameters.run_app >>
    jobs:
      - build:
          name: app-build
          package_name: app
      - deploy:
          name: app-deploy
          package_name: app
          requires:
            - app-build
  gateway:
    when: << pipeline.parameters.run_gateway >>
    jobs:
      - build:
          name: gateway-build
          package_name: gateway
      - deploy:
          name: gateway-deploy
          package_name: gateway
          requires:
            - gateway-build


parameters:
  run_api:
    default: false
    type: boolean
  run_app:
    default: false
    type: boolean
  run_gateway:
    default: false
    type: boolean
  run_trigger_workflow:
    default: true
    type: boolean
  swissknife_sha:
    default: ""
    type: string